"""Database module for TradingDashboard."""
from .database import (
    get_db,
    init_db,
    close_db,
    DatabaseSession,
)
from .models import (
    Base,
    AppConfig,
    UserPreferences,
    TradingAnalysis,
    PriceForecast,
    Watchlist,
    WatchlistItem,
    PriceAlert,
    TradeJournalEntry,
)
from .repository import (
    ConfigRepository,
    UserPreferencesRepository,
    TradingAnalysisRepository,
    PriceForecastRepository,
    WatchlistRepository,
    PriceAlertRepository,
    TradeJournalRepository,
)
from .schemas import (
    ConfigValueRequest,
    ConfigResponse,
    ConfigListResponse,
    UserPreferencesRequest,
    UserPreferencesResponse,
    TradingAnalysisCreate,
    TradingAnalysisResponse,
    TradingAnalysisListResponse,
    PriceForecastCreate,
    PriceForecastResponse,
    WatchlistCreate,
    WatchlistUpdate,
    WatchlistItemAdd,
    WatchlistItemResponse,
    WatchlistResponse,
    PriceAlertCreate,
    PriceAlertResponse,
    TradeJournalCreate,
    TradeJournalUpdate,
    TradeJournalClose,
    TradeJournalResponse,
    TradeStatisticsResponse,
    BackupMetadata,
    BackupData,
    RestoreRequest,
    RestoreResult,
)

__all__ = [
    # Database connection
    "get_db",
    "init_db",
    "close_db",
    "DatabaseSession",
    # Models
    "Base",
    "AppConfig",
    "UserPreferences",
    "TradingAnalysis",
    "PriceForecast",
    "Watchlist",
    "WatchlistItem",
    "PriceAlert",
    "TradeJournalEntry",
    # Repositories
    "ConfigRepository",
    "UserPreferencesRepository",
    "TradingAnalysisRepository",
    "PriceForecastRepository",
    "WatchlistRepository",
    "PriceAlertRepository",
    "TradeJournalRepository",
    # Schemas
    "ConfigValueRequest",
    "ConfigResponse",
    "ConfigListResponse",
    "UserPreferencesRequest",
    "UserPreferencesResponse",
    "TradingAnalysisCreate",
    "TradingAnalysisResponse",
    "TradingAnalysisListResponse",
    "PriceForecastCreate",
    "PriceForecastResponse",
    "WatchlistCreate",
    "WatchlistUpdate",
    "WatchlistItemAdd",
    "WatchlistItemResponse",
    "WatchlistResponse",
    "PriceAlertCreate",
    "PriceAlertResponse",
    "TradeJournalCreate",
    "TradeJournalUpdate",
    "TradeJournalClose",
    "TradeJournalResponse",
    "TradeStatisticsResponse",
    "BackupMetadata",
    "BackupData",
    "RestoreRequest",
    "RestoreResult",
]
